SHOP_ITEMS = [
    {'name': 'aloe_plant', 'display': 'Aloe plant', 'cost': 35, 'src': '/static/images/decor/aloe_plant/aloe_plant.png', 'overlap': 'curtains'},
    {'name': 'blue_jar', 'display': 'Blue jar', 'cost': 10, 'src': '/static/images/decor/blue_jar/blue_jar.png', 'overlap': None},
    {'name': 'books', 'display': 'Books', 'cost': 20, 'src': '/static/images/decor/books/books.png', 'overlap': None},
    {'name': 'bottle', 'display': 'Bottle', 'cost': 10, 'src': '/static/images/decor/bottle/bottle.png', 'overlap': None},
    {'name': 'cuckoo_clock', 'display': 'Cuckoo clock', 'cost': 75, 'src': '/static/images/decor/cuckoo_clock/cuckoo_clock.png', 'overlap': None},
    {'name': 'curtains', 'display': 'Curtains', 'cost': 50, 'src': '/static/images/decor/curtains/curtains.png', 'overlap': None},
    {'name': 'cutting_board', 'display': 'Cutting board', 'cost': 10, 'src': '/static/images/decor/cutting_board/cutting_board.png', 'overlap': None},
    {'name': 'floor_mat', 'display': 'Floor mat', 'cost': 75, 'src': '/static/images/decor/floor_mat/floor_mat.png', 'overlap': None},
    {'name': 'hanging_plant', 'display': 'Hanging plant', 'cost': 50, 'src': '/static/images/decor/hanging_plant/hanging_plant.png', 'overlap': 'curtains'},
    {'name': 'kettle', 'display': 'Kettle', 'cost': 35, 'src': '/static/images/decor/kettle/kettle.png', 'overlap': None},
    {'name': 'kitchen_towel', 'display': 'Kitchen towel', 'cost': 20, 'src': '/static/images/decor/kitchen_towel/kitchen_towel.png', 'overlap': None},
    {'name': 'mixing_bowls', 'display': 'Mixing bowls', 'cost': 20, 'src': '/static/images/decor/mixing_bowls/mixing_bowls.png', 'overlap': None},
    {'name': 'mortar_pestle', 'display': 'Mortar & pestle', 'cost': 35, 'src': '/static/images/decor/mortar_pestle/mortar_pestle.png', 'overlap': None},
    {'name': 'mugs', 'display': 'Mugs', 'cost': 10, 'src': '/static/images/decor/mugs/mugs.png', 'overlap': None},
    {'name': 'painting', 'display': 'Painting', 'cost': 75, 'src': '/static/images/decor/painting/painting.png', 'overlap': None},
    {'name': 'pink_jar', 'display': 'Pink jar', 'cost': 10, 'src': '/static/images/decor/pink_jar/pink_jar.png', 'overlap': None},
    {'name': 'pothos_plant', 'display': 'Pothos plant', 'cost': 50, 'src': '/static/images/decor/pothos_plant/pothos_plant.png', 'overlap': 'books'},
    {'name': 'potted_fern', 'display': 'Potted fern', 'cost': 50, 'src': '/static/images/decor/potted_fern/potted_fern.png', 'overlap': None},
    {'name': 'potted_tree', 'display': 'Potted tree', 'cost': 100, 'src': '/static/images/decor/potted_tree/potted_tree.png', 'overlap': None},
    {'name': 'rice_jar', 'display': 'Rice jar', 'cost': 20, 'src': '/static/images/decor/rice_jar/rice_jar.png', 'overlap': None},
    {'name': 'soap_dispenser', 'display': 'Soap dispenser', 'cost': 10, 'src': '/static/images/decor/soap_dispenser/soap_dispenser.png', 'overlap': None},
    {'name': 'tiger_statue', 'display': 'Tiger statue', 'cost': 100, 'src': '/static/images/decor/tiger_statue/tiger_statue.png', 'overlap': 'yellow_jar'},
    {'name': 'utensils', 'display': 'Utensils', 'cost': 35, 'src': '/static/images/decor/utensils/utensils.png', 'overlap': None},
    {'name': 'yellow_jar', 'display': 'Yellow jar', 'cost': 10, 'src': '/static/images/decor/yellow_jar/yellow_jar.png', 'overlap': None},
]
